"""5-second smoke test for the lite path.

Verifies the full stack works end-to-end in-process — no Docker, no servers.
Run via `make verify-lite` or `python scripts/verify_lite.py`.

Exit code 0 on success; non-zero on first failure.
"""
from __future__ import annotations

import sys
import traceback
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def step(label: str) -> None:
    print(f"  • {label}")


def main() -> int:
    print("Day 19 lite smoke test")
    try:
        # ── 1. fastembed ────────────────────────────────────────────────
        step("fastembed loads + embeds (BAAI/bge-small-en-v1.5)")
        from fastembed import TextEmbedding
        emb_model = TextEmbedding(model_name="BAAI/bge-small-en-v1.5")
        sample = list(emb_model.embed(["cloud computing tiếng Việt"]))
        assert len(sample) == 1 and len(sample[0]) == 384, f"unexpected vector shape: {len(sample[0])}"

        # ── 2. Qdrant in-memory ─────────────────────────────────────────
        step("Qdrant in-memory: index + search")
        from qdrant_client import QdrantClient
        from qdrant_client.models import Distance, VectorParams, PointStruct
        client = QdrantClient(":memory:")
        client.create_collection(
            collection_name="smoke",
            vectors_config=VectorParams(size=384, distance=Distance.COSINE),
        )
        client.upsert(
            collection_name="smoke",
            points=[PointStruct(id=i, vector=sample[0].tolist(), payload={"i": i}) for i in range(3)],
        )
        hits = client.query_points(collection_name="smoke", query=sample[0].tolist(), limit=2).points
        assert len(hits) == 2, f"expected 2 hits, got {len(hits)}"

        # ── 3. rank-bm25 ────────────────────────────────────────────────
        step("rank-bm25 scores documents")
        from rank_bm25 import BM25Okapi
        corpus = ["cloud computing đám mây", "machine learning mô hình", "database cơ sở dữ liệu"]
        bm25 = BM25Okapi([d.split() for d in corpus])
        scores = bm25.get_scores("cloud".split())
        assert scores[0] > scores[1], "BM25 should rank doc 0 (cloud) above doc 1"

        # ── 4. corpus + golden set present ──────────────────────────────
        step("Corpus + golden set generated by seed_corpus.py")
        corpus_path = ROOT / "data" / "corpus_vn.jsonl"
        golden_path = ROOT / "data" / "golden_set.jsonl"
        assert corpus_path.exists(), f"missing {corpus_path} — run `make seed`"
        assert golden_path.exists(), f"missing {golden_path}"
        n_docs = sum(1 for _ in corpus_path.open(encoding="utf-8"))
        n_golden = sum(1 for _ in golden_path.open(encoding="utf-8"))
        assert n_docs == 1000, f"expected 1000 docs, got {n_docs}"
        assert n_golden == 50, f"expected 50 golden queries, got {n_golden}"

        # ── 5. Feast registry init (SQLite + file) ──────────────────────
        step("Feast can init a local registry (SQLite online + file offline)")
        # Lazy import: feast pulls in pyarrow + pandas; keep startup fast.
        from feast import FeatureStore  # noqa: F401
        # We don't `feast apply` here — that's exercise 04. Just confirm import.

        # ── 6. FastAPI app imports ──────────────────────────────────────
        step("FastAPI app imports without error")
        sys.path.insert(0, str(ROOT))
        from app import main as app_main
        assert hasattr(app_main, "app"), "app.main.app missing"

        # ── 7. advanced-mission modules (NB5-NB8) ───────────────────────
        step("Advanced modules import + behave (metadata, filters, cache, agent, features)")
        from app.agent import SEARCH_TOOL
        from app.cache import SemanticCache  # noqa: F401
        from app.metadata import doc_metadata
        from app.features import auc, generate_events, leakage_experiment
        import numpy as np

        # metadata must be stable across processes, or the rubric is ungradable
        assert doc_metadata("cloud_000") == doc_metadata("cloud_000")

        # the tool enum must match the corpus, or every topic filter silently
        # returns zero results
        corpus_topics = set()
        with corpus_path.open(encoding="utf-8") as f:
            import json as _json
            for line in f:
                corpus_topics.add(_json.loads(line)["topic"])
        enum = SEARCH_TOOL["input_schema"]["properties"]["topic"]["enum"]
        missing = [t for t in enum if t not in corpus_topics]
        assert not missing, f"tool enum has topics absent from corpus: {missing}"

        # auc sanity + the leakage lesson still reproduces
        assert abs(auc(np.array([1.0, 2, 3, 4]), np.array([0, 0, 1, 1])) - 1.0) < 1e-9
        ev = generate_events(n_users=40, n_days=10, seed=42)
        gap = leakage_experiment(ev, "session_id").set_index("encoding").loc["target-naive", "gap"]
        assert gap > 0.20, f"target-encoding leak demo no longer reproduces (gap={gap:.3f})"

        print("\nAll checks passed — lite path is ready. Run `make api` then `make benchmark`.")
        return 0
    except Exception as exc:  # noqa: BLE001
        print(f"\nSmoke test FAILED: {type(exc).__name__}: {exc}")
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
